name: JSB_tools_3.9
channels:
  - conda-forge
dependencies:
  - root    # Problem on Windows
  - openmc  # Problem on Windows
  - python=3.9
  - numpy
  - scipy
  - uncertainties
  - matplotlib
  - sortedcontainers
  - bitstring
  - pandas
  - plotly
  - lmfit
  - pip
  - pip:
    - winfiletime
    - sortednp
