#name: openmc
# Command: mamba env update -c conda-forge --file ~/PycharmProjects/JSB_tools/environment.yml --prune  --name env_name
channels:
  - conda-forge
dependencies:
#  - root    # Do manually and probably dont install both in save environment. Problem on Windows
#  - openmc  # Problem on Windows
  - numpy
  - numba
  - numdifftools
  - scipy
  - uncertainties
  - matplotlib
  - sortedcontainers
  - pandas
  - openssl
  - lmfit
  - bs4
  - lxml
## Uncomment below whe doing a routine installation
#  - pip:
#    - sortednp
#    - bitstring