name: JSB_tools_3.9
channels:
  - conda-forge
dependencies:
  - root    # Problem on Windows
  - openmc  # Problem on Windows
  - python=3.9
  - numpy=1.23.3
  - numdifftools  # for lmfit internal
  - scipy
  - uncertainties
  - matplotlib
  - sortedcontainers
  - bitstring
  - pandas
  - plotly
  - lmfit
  - pip
  - pip:
    - filetime
    - sortednp
    - bitstring
