name: JSB_tools_3.9
channels:
  - conda-forge
dependencies:
#  - root    # Problem on Windows
#  - openmc  # Problem on Windows
  - numpy
  - numdifftools  # for lmfit internal
  - scipy
  - uncertainties
  - matplotlib
  - sortedcontainers
  - pandas
  - lmfit
  - bs4
  - pip
  - numba
  - pip:
    - filetime
    - sortednp
    - bitstring